### ISSUE TITLE
Virt-Manager Issue after using sudo ./make.sh --add

### ISSUE THREAD

**Issue by ShawZam** [notAperson535/OneClick-macOS-Simple-KVM#119]
-macOS Sonoma VM
host
-AMD Ryzen 7 6800H 
-Ubuntu 24.04 LTS
-Virt-Manager 4.1.0

Virt-Manager details:
Error starting domain: internal error: QEMU unexpectedly closed the monitor (vm='macOS-Simple-KVM'): 2024-09-02T07:15:01.607559Z qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.01H:ECX.pcid [bit 17]
2024-09-02T07:15:01.607566Z qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.07H:EBX.hle [bit 4]
2024-09-02T07:15:01.607571Z qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.07H:EBX.rtm [bit 11]
2024-09-02T07:15:01.607801Z qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.01H:ECX.pcid [bit 17]
2024-09-02T07:15:01.607808Z qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.07H:EBX.hle [bit 4]
2024-09-02T07:15:01.607813Z qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.07H:EBX.rtm [bit 11]
2024-09-02T07:15:01.614165Z qemu-system-x86_64: -device hda-output: no default audio driver available
Perhaps you wanted to use -audio or set audiodev=audio1?

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 72, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 108, in tmpcb
    callback(*args, **kwargs)
  File "/usr/share/virt-manager/virtManager/object/libvirtobject.py", line 57, in newfn
    ret = fn(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/virt-manager/virtManager/object/domain.py", line 1402, in startup
    self._backend.create()
  File "/usr/lib/python3/dist-packages/libvirt.py", line 1379, in create
    raise libvirtError('virDomainCreate() failed')
libvirt.libvirtError: internal error: QEMU unexpectedly closed the monitor (vm='macOS-Simple-KVM'): 2024-09-02T07:15:01.607559Z qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.01H:ECX.pcid [bit 17]
2024-09-02T07:15:01.607566Z qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.07H:EBX.hle [bit 4]
2024-09-02T07:15:01.607571Z qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.07H:EBX.rtm [bit 11]
2024-09-02T07:15:01.607801Z qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.01H:ECX.pcid [bit 17]
2024-09-02T07:15:01.607808Z qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.07H:EBX.hle [bit 4]
2024-09-02T07:15:01.607813Z qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.07H:EBX.rtm [bit 11]
2024-09-02T07:15:01.614165Z qemu-system-x86_64: -device hda-output: no default audio driver available
Perhaps you wanted to use -audio or set audiodev=audio1?

**Comment by iTrooz** [comment]
Same issue with
-macOS Sonoma VM
host
-13th Gen Intel(R) Core(TM) i7-1365U
-ArchLinux
-Virt-Manager 5.0.0
- virsh 10.10.0

**Comment by iTrooz** [comment]
I found how to fix it !

Remove these lines from the virsh VM definition (by doing something like `virsh edit macOS-Simple-KVM`):
```yml
    <qemu:arg value="-device"/>
    <qemu:arg value="intel-hda"/>
    <qemu:arg value="-device"/>
    <qemu:arg value="hda-output"/>
```

**Comment by notAperson535** [comment]
@iTrooz could you submit a PR with those lines removed so I can give credit for finding the issue? If not I can always add the fix.

**Comment by iTrooz** [comment]
Sure !
But I removed the lines without understanding what they do. Didn't you add them for a reason ?

**Comment by notAperson535** [comment]
@iTrooz They’re meant to be audio devices but they don’t work the best and have been causing issues. Anyone familiar with virt manager can add them back in a few clicks.

**Comment by iTrooz** [comment]
Alright, I'll submit a PR tomorrow!
