### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by tiredsemanticist** [notAperson535/OneClick-macOS-Simple-KVM#123]
I'm trying to run macOS Monterey (my host system is running Pop!_OS 22.04 LTS, which is based on Ubuntu 22.04 LTS), and I get the following error message when I try to power on the virtual machine:

> Error starting domain: operation failed: unable to find any master var store for loader: /home/lnik/Desktop/OneClick-macOS-Simple-KVM-master/firmware/OVMF_CODE.fd
> 
> Traceback (most recent call last):
>   File "/usr/share/virt-manager/virtManager/asyncjob.py", line 72, in cb_wrapper
>     callback(asyncjob, *args, **kwargs)
>   File "/usr/share/virt-manager/virtManager/asyncjob.py", line 108, in tmpcb
>     callback(*args, **kwargs)
>   File "/usr/share/virt-manager/virtManager/object/libvirtobject.py", line 57, in newfn
>     ret = fn(self, *args, **kwargs)
>   File "/usr/share/virt-manager/virtManager/object/domain.py", line 1384, in startup
>     self._backend.create()
>   File "/usr/lib/python3/dist-packages/libvirt.py", line 1353, in create
>     raise libvirtError('virDomainCreate() failed')
> libvirt.libvirtError: operation failed: unable to find any master var store for loader: /home/lnik/Desktop/OneClick-macOS-Simple-KVM-master/firmware/OVMF_CODE.fd

I'm guessing did something wrong, but I can't figure out what... I followed the installation instructions word-for-word. I also made sure I have the newest iteration of OVMF_CODE.fd

**Comment by notAperson535** [comment]
@tiredsemanticist try downloading [this](https://github.com/notAperson535/OneClick-macOS-Simple-KVM/raw/70b1475c8d15c2f355a36644307ecacf595daa85/firmware/OVMF_VARS-1024x768.fd) into your firmware folder and tell me if it works. If it does not, you could also try running the VM as sudo to see what happens.

**Comment by tiredsemanticist** [comment]
@notAperson535 I tried both and only got halfway to a solution. Had to rename that file to OVMF_VARS.fd to get virt-manager to acknowledge it, and then the machine powered on... Unfortunately, there's no installer option in OpenCore even though I made sure that all the correct hardware has been added to the virtual machine. Running as sudo makes no difference

![Screenshot_macOS-Simple-KVM_2024-11-05_21:37:48](https://github.com/user-attachments/assets/c6d3cf9c-2d59-43a9-907e-d0be7a676044)

1000% willing to believe that I'm doing something wrong, I just haven't been able to figure out what. 😅
