### ISSUE TITLE
VM does not start from virt-manager

### ISSUE THREAD

**Issue by welcoMattic** [notAperson535/OneClick-macOS-Simple-KVM#63]
**Which operating system are you trying to install?**
e.g. macOS Ventura

**Describe the bug**

Warning message by running `./basic.sh`

```
qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.07H:EBX.hle [bit 4]
qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.07H:EBX.rtm [bit 11]
qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.07H:EBX.hle [bit 4]
qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.07H:EBX.rtm [bit 11]
qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.07H:EBX.hle [bit 4]
qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.07H:EBX.rtm [bit 11]
qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.07H:EBX.hle [bit 4]
qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.07H:EBX.rtm [bit 11]
```

But the VM starts.

And in virt-manager, same messages but as errors, and the VM does not start.

**To Reproduce**
Follow the documentation to create a fresh new VM
Run `./make.sh --add`
Try to run the VM from virt-manager

**Expected behavior**
The VM to boot normally, like by running basic.sh

**Desktop (please complete the following information):**
 - OS: Arch
 - Version kernel 6.1

**Comment by jon-bit** [comment]
I'm having the same problem. Anyone know how to fix this?

**Comment by notAperson535** [comment]
@welcoMattic @jon-bit Did you add the macos.qow2 disk to virt-manager?

**Comment by jon-bit** [comment]
Sorry but how would I go about that?

**Comment by jon-bit** [comment]
Found it but what bus type do I use?

**Comment by jon-bit** [comment]
Never mind did not work. I just tried them all.

**Comment by jon-bit** [comment]
here is my full log for when I try to start it in vit-manger
```
Error starting domain: internal error: qemu unexpectedly closed the monitor: 2023-01-19T04:24:40.358934Z qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.07H:EBX.rtm [bit 11]
2023-01-19T04:24:40.359119Z qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.07H:EBX.hle [bit 4]
2023-01-19T04:24:40.359125Z qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.07H:EBX.rtm [bit 11]
2023-01-19T04:24:40.359302Z qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.07H:EBX.hle [bit 4]
2023-01-19T04:24:40.359307Z qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.07H:EBX.rtm [bit 11]
audio: Device hda: audiodev default parameter is deprecated, please specify audiodev=audio1
2023-01-19T04:24:40.370817Z qemu-system-x86_64: -device {"driver":"qxl-vga","id":"video0","max_outputs":1,"ram_size":67108864,"vram_size":67108864,"vram64_size_mb":0,"vgamem_mb":16,"bus":"pcie.0","addr":"0x1"}: PCI: slot 1 function 0 not available for qxl-vga, in use by intel-hda,id=(null)

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 72, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 108, in tmpcb
    callback(*args, **kwargs)
  File "/usr/share/virt-manager/virtManager/object/libvirtobject.py", line 57, in newfn
    ret = fn(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/virt-manager/virtManager/object/domain.py", line 1402, in startup
    self._backend.create()
  File "/usr/lib64/python3.11/site-packages/libvirt.py", line 1362, in create
    raise libvirtError('virDomainCreate() failed')
libvirt.libvirtError: internal error: qemu unexpectedly closed the monitor: 2023-01-19T04:24:40.358934Z qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.07H:EBX.rtm [bit 11]
2023-01-19T04:24:40.359119Z qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.07H:EBX.hle [bit 4]
2023-01-19T04:24:40.359125Z qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.07H:EBX.rtm [bit 11]
2023-01-19T04:24:40.359302Z qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.07H:EBX.hle [bit 4]
2023-01-19T04:24:40.359307Z qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.07H:EBX.rtm [bit 11]
audio: Device hda: audiodev default parameter is deprecated, please specify audiodev=audio1
2023-01-19T04:24:40.370817Z qemu-system-x86_64: -device {"driver":"qxl-vga","id":"video0","max_outputs":1,"ram_size":67108864,"vram_size":67108864,"vram64_size_mb":0,"vgamem_mb":16,"bus":"pcie.0","addr":"0x1"}: PCI: slot 1 function 0 not available for qxl-vga, in use by intel-hda,id=(null)
```

**Comment by welcoMattic** [comment]
I've tried to remove qxl, but it is still unable to boot:

```Error starting domain: internal error: qemu unexpectedly closed the monitor: 2023-01-19T14:11:14.321051Z qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.07H:EBX.rtm [bit 11]
2023-01-19T14:11:14.321217Z qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.07H:EBX.hle [bit 4]
2023-01-19T14:11:14.321221Z qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.07H:EBX.rtm [bit 11]
2023-01-19T14:11:14.321393Z qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.07H:EBX.hle [bit 4]
2023-01-19T14:11:14.321397Z qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.07H:EBX.rtm [bit 11]
audio: Device hda: audiodev default parameter is deprecated, please specify audiodev=audio1
2023-01-19T14:11:14.337307Z qemu-system-x86_64: -device {"driver":"VGA","id":"video0","vgamem_mb":16,"bus":"pcie.0","addr":"0x1"}: PCI: slot 1 function 0 not available for VGA, in use by intel-hda,id=(null)

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 72, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 108, in tmpcb
    callback(*args, **kwargs)
  File "/usr/share/virt-manager/virtManager/object/libvirtobject.py", line 57, in newfn
    ret = fn(self, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/object/domain.py", line 1402, in startup
    self._backend.create()
  File "/usr/lib/python3.10/site-packages/libvirt.py", line 1373, in create
    raise libvirtError('virDomainCreate() failed')
libvirt.libvirtError: internal error: qemu unexpectedly closed the monitor: 2023-01-19T14:11:14.321051Z qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.07H:EBX.rtm [bit 11]
2023-01-19T14:11:14.321217Z qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.07H:EBX.hle [bit 4]
2023-01-19T14:11:14.321221Z qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.07H:EBX.rtm [bit 11]
2023-01-19T14:11:14.321393Z qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.07H:EBX.hle [bit 4]
2023-01-19T14:11:14.321397Z qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.07H:EBX.rtm [bit 11]
audio: Device hda: audiodev default parameter is deprecated, please specify audiodev=audio1
2023-01-19T14:11:14.337307Z qemu-system-x86_64: -device {"driver":"VGA","id":"video0","vgamem_mb":16,"bus":"pcie.0","addr":"0x1"}: PCI: slot 1 function 0 not available for VGA, in use by intel-hda,id=(null)
```

I replace the video model by VGA or virtio : same error.

**Comment by pedrohqb** [comment]
I am having the same issue. It seems to be a qemu bug.

**Comment by mbaldessari** [comment]
Something like https://lore.kernel.org/qemu-devel/20221208062513.2589476-1-xiaoyao.li@intel.com/ is probably needed to fix this in qemu, although I assume it might depend on which CPU you're running

**Comment by DeeeeLAN** [comment]
I made the warnings/errors go away by changing the `-cpu Haswell... \` line to `-cpu host \`, which works on my system but I am not sure about others.

**Comment by notAperson535** [comment]
I don't think the warnings really matter though, they don't seem to effect anything

**Comment by funjay** [comment]
> I've tried to remove qxl, but it is still unable to boot:
> 
> ```
> 2023-01-19T14:11:14.321217Z qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.07H:EBX.hle [bit 4]
> 2023-01-19T14:11:14.321221Z qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.07H:EBX.rtm [bit 11]
> 2023-01-19T14:11:14.321393Z qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.07H:EBX.hle [bit 4]
> 2023-01-19T14:11:14.321397Z qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.07H:EBX.rtm [bit 11]
> audio: Device hda: audiodev default parameter is deprecated, please specify audiodev=audio1
> 2023-01-19T14:11:14.337307Z qemu-system-x86_64: -device {"driver":"VGA","id":"video0","vgamem_mb":16,"bus":"pcie.0","addr":"0x1"}: PCI: slot 1 function 0 not available for VGA, in use by intel-hda,id=(null)
> 
> Traceback (most recent call last):
>   File "/usr/share/virt-manager/virtManager/asyncjob.py", line 72, in cb_wrapper
>     callback(asyncjob, *args, **kwargs)
>   File "/usr/share/virt-manager/virtManager/asyncjob.py", line 108, in tmpcb
>     callback(*args, **kwargs)
>   File "/usr/share/virt-manager/virtManager/object/libvirtobject.py", line 57, in newfn
>     ret = fn(self, *args, **kwargs)
>   File "/usr/share/virt-manager/virtManager/object/domain.py", line 1402, in startup
>     self._backend.create()
>   File "/usr/lib/python3.10/site-packages/libvirt.py", line 1373, in create
>     raise libvirtError('virDomainCreate() failed')
> libvirt.libvirtError: internal error: qemu unexpectedly closed the monitor: 2023-01-19T14:11:14.321051Z qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.07H:EBX.rtm [bit 11]
> 2023-01-19T14:11:14.321217Z qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.07H:EBX.hle [bit 4]
> 2023-01-19T14:11:14.321221Z qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.07H:EBX.rtm [bit 11]
> 2023-01-19T14:11:14.321393Z qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.07H:EBX.hle [bit 4]
> 2023-01-19T14:11:14.321397Z qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.07H:EBX.rtm [bit 11]
> audio: Device hda: audiodev default parameter is deprecated, please specify audiodev=audio1
> 2023-01-19T14:11:14.337307Z qemu-system-x86_64: -device {"driver":"VGA","id":"video0","vgamem_mb":16,"bus":"pcie.0","addr":"0x1"}: PCI: slot 1 function 0 not available for VGA, in use by intel-hda,id=(null)
> ```
> 
> I replace the video model by VGA or virtio : same error.

Your issue is the hda as the error says, 
Quick fix, remove the hda settings in your virtm xml properties
or 
fullfix, add the audiodev value (read the docs)

thanks

**Comment by ericek111** [comment]
Just change the PCI slot number for the virtual GPU. 0x08 works for me, like this:
```
    <video>
      <model type="qxl" ram="65536" vram="65536" vgamem="16384" heads="1" primary="yes"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x08" function="0x0"/>
    </video>
```

**Comment by Val-d-emar** [comment]
I have like that problem too on AMD Rysen 3:

```Ошибка запуска домена: внутренняя ошибка: QEMU неожиданно завершил работу монитора: 2024-10-15T08:28:48.779266Z qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.01H:ECX.pcid [bit 17]
2024-10-15T08:28:48.779273Z qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.07H:EBX.hle [bit 4]
2024-10-15T08:28:48.779278Z qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.07H:EBX.erms [bit 9]
2024-10-15T08:28:48.779284Z qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.07H:EBX.invpcid [bit 10]
2024-10-15T08:28:48.779289Z qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.07H:EBX.rtm [bit 11]
audio: Device hda: audiodev default parameter is deprecated, please specify audiodev=audio1
2024-10-15T08:28:48.789949Z qemu-system-x86_64: -device {"driver":"qxl-vga","id":"video0","max_outputs":1,"ram_size":67108864,"vram_size":67108864,"vram64_size_mb":0,"vgamem_mb":16,"bus":"pcie.0","addr":"0x1"}: PCI: slot 1 function 0 not available for qxl-vga, in use by intel-hda,id=(null)

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 72, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 108, in tmpcb
    callback(*args, **kwargs)
  File "/usr/share/virt-manager/virtManager/object/libvirtobject.py", line 57, in newfn
    ret = fn(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/virt-manager/virtManager/object/domain.py", line 1402, in startup
    self._backend.create()
  File "/usr/lib/python3/dist-packages/libvirt.py", line 1373, in create
    raise libvirtError('virDomainCreate() failed')
libvirt.libvirtError: внутренняя ошибка: QEMU неожиданно завершил работу монитора: 2024-10-15T08:28:48.779266Z qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.01H:ECX.pcid [bit 17]
2024-10-15T08:28:48.779273Z qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.07H:EBX.hle [bit 4]
2024-10-15T08:28:48.779278Z qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.07H:EBX.erms [bit 9]
2024-10-15T08:28:48.779284Z qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.07H:EBX.invpcid [bit 10]
2024-10-15T08:28:48.779289Z qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.07H:EBX.rtm [bit 11]
audio: Device hda: audiodev default parameter is deprecated, please specify audiodev=audio1
2024-10-15T08:28:48.789949Z qemu-system-x86_64: -device {"driver":"qxl-vga","id":"video0","max_outputs":1,"ram_size":67108864,"vram_size":67108864,"vram64_size_mb":0,"vgamem_mb":16,"bus":"pcie.0","addr":"0x1"}: PCI: slot 1 function 0 not available for qxl-vga, in use by intel-hda,id=(null)```
